# You can (and should) edit this file!
## (This is your own copy of the file, it won't impact anybody else's)
### (This is the CS2810 Python/Numpy Linear Algebra Calculator)

1. Replace the `# your python code here` with your own python code
    - Forget exactly what syntax to use to get the job done?   Please see the examples below.
1. Hover your mouse over the cell you've just edited and click the "play" triangle to run the code
    - by default, the last line's output (if any) is shown.  So compute on this final line to observe your output

In [1]:
import numpy as np
import sympy

# your python code here!

## Initializing matrices

In [2]:
# build a 2d matrix (first row is [1, 2 ,3])
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
x.shape

(2, 3)

In [3]:
# build a row vector
row_vec = np.array([[1, 2, 3]])
row_vec.shape

(1, 3)

In [4]:
# build a column vector
col_vec = np.array([[1], [2], [3]])
col_vec.shape

(3, 1)

In [5]:
# use tranpose to build a column vector and not deal with as many [][][][][][]
col_vec2 = row_vec.T
col_vec2.shape

(3, 1)

In [6]:
# numpy has 1d matrices (which aren't really a math construction but a programming one)
# they act as row / col vector when matrix multiplied depending on whats necessary
# I suggest you avoid them initially to avoid accidentally violating the shape rule
dangerous_vec = np.array([1, 2, 3])
dangerous_vec.shape

(3,)

# Reduced Row Echelon Form

In [7]:
# reduced row echelon form
# (swap in your preferred augmented matrix (with augment col) for x below)
import sympy

sympy.Matrix(x).rref()[0]

Matrix([
[1, 0, -1],
[0, 1,  2]])

## Eigenvalue / Eigenvectors

In [14]:
import numpy as np

a = np.array([[1, 5], [2, 4]])
a

array([[1, 5],
       [2, 4]])

In [15]:
# compute eigenvalues and eigenvectors
eig_val, eig_vec = np.linalg.eig(a)

# these are the eigenvalues of a
eig_val

array([-1.,  6.])

In [16]:
# each col of matrix below is an eigenvector of a
# note: first column corresponds to first eigenvector in `eig_vec` and so on
eig_vec

array([[-0.92847669, -0.70710678],
       [ 0.37139068, -0.70710678]])

In [19]:
# matrix above is tough to read ... numpy returns eigenvectors with length 1
v = eig_vec[:, 0]
v

array([-0.92847669,  0.37139068])

In [22]:
# pro-tip: divide the vector by the smallest absolute value entry and it'll clean up a bit
# (remember: all scaled versions of eigenvector are also eigenvectors, so this scaling is appropriate)
v_cleaner = v / np.abs(v).min()
v_cleaner

array([-2.5,  1. ])

In [24]:
# remember: Av = \lambda v
a @ v_cleaner

array([ 2.5, -1. ])

# Matrix Operations

In [8]:
# lets remind ourselves what x is so we can see the operations "before" clearly
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# matrix addition (add corresponding entries)
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
# scalar multiplication (scale each entry by same value)
x * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [11]:
# reminding ourselves what col_vec is before we use it ...
col_vec

array([[1],
       [2],
       [3]])

In [12]:
# matrix multiplication (many definitions ... my favorite sub-type to remember is:
# A MATRIX-VECTOR MULTIPLICATION IS A LINEAR COMBINATION OF THE COLUMNS OF THE MATRIX ... :)
x @ col_vec

array([[14],
       [32]])

# Special Matrices

In [13]:
# just a new example x
x = np.array([[1, 2], [3, 4]])

In [14]:
# inverse
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
# transpose (just as shown above)
x.T

array([[1, 3],
       [2, 4]])

# Saving/Loading a `csv` file as a matrix
Datasets with 100s of rows / cols shouldn't be typed out each time.  Instead, save as a spreadsheet (must be comma seperated value: `csv`) and then load whenever needed.

In [16]:
a = np.array([[1,2,3],
              [4,5,6], 
              [7,8,9]])

# saves matrix a as a csv
np.savetxt('matrix_a.csv', a, delimiter=',')

# load matrix from a csv
another_a = np.genfromtxt('matrix_a.csv', delimiter=',')
another_a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])